server:
  port: 4160

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '416416'
    url: jdbc:mysql://localhost:3306/code2025?useUnicode=true&characterEncoding=utf8&useSSL=false


mybatis:
  # 映射xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
